<?php

namespace Database\Seeders;

use App\Models\Country;
use App\Models\Region;
use Illuminate\Database\Seeder;

class RegionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $regionsByCountry = $this->getRegionsByCountry();

        foreach ($regionsByCountry as $countryCode => $regions) {
            $country = Country::query()->where('code', $countryCode)->first();

            if (! $country) {
                continue;
            }

            foreach ($regions as $regionName) {
                Region::query()->create([
                    'country_id' => $country->id,
                    'name' => $regionName,
                ]);
            }
        }
    }

    /**
     * Get all regions grouped by country code.
     *
     * @return array<string, list<string>>
     */
    private function getRegionsByCountry(): array
    {
        return [
            // Europe
            'PT' => [
                'Lisboa',
                'Porto',
                'Braga',
                'Coimbra',
                'Faro',
                'Aveiro',
                'Setúbal',
                'Funchal',
                'Évora',
                'Leiria',
                'Viseu',
                'Guimarães',
            ],
            'GB' => [
                'London',
                'Manchester',
                'Birmingham',
                'Edinburgh',
                'Glasgow',
                'Bristol',
                'Liverpool',
                'Leeds',
                'Sheffield',
                'Newcastle',
                'Cardiff',
                'Belfast',
                'Nottingham',
                'Southampton',
            ],
            'DE' => [
                'Berlin',
                'Munich',
                'Hamburg',
                'Frankfurt',
                'Cologne',
                'Düsseldorf',
                'Stuttgart',
                'Leipzig',
                'Dresden',
                'Hannover',
                'Nuremberg',
                'Bremen',
                'Dortmund',
                'Essen',
            ],
            'ES' => [
                'Madrid',
                'Barcelona',
                'Valencia',
                'Seville',
                'Bilbao',
                'Málaga',
                'Zaragoza',
                'Palma',
                'Las Palmas',
                'Murcia',
                'Alicante',
                'Granada',
                'San Sebastián',
                'A Coruña',
            ],
            'FR' => [
                'Paris',
                'Lyon',
                'Marseille',
                'Toulouse',
                'Nice',
                'Nantes',
                'Strasbourg',
                'Montpellier',
                'Bordeaux',
                'Lille',
                'Rennes',
                'Grenoble',
                'Dijon',
                'Angers',
            ],
            'IT' => [
                'Rome',
                'Milan',
                'Naples',
                'Turin',
                'Florence',
                'Bologna',
                'Venice',
                'Verona',
                'Genoa',
                'Palermo',
                'Bari',
                'Catania',
                'Trieste',
                'Parma',
            ],
            'SE' => [
                'Stockholm',
                'Gothenburg',
                'Malmö',
                'Uppsala',
                'Västerås',
                'Örebro',
                'Linköping',
                'Helsingborg',
                'Jönköping',
                'Norrköping',
                'Lund',
                'Umeå',
            ],
            'NL' => [
                'Amsterdam',
                'Rotterdam',
                'The Hague',
                'Utrecht',
                'Eindhoven',
                'Groningen',
                'Tilburg',
                'Almere',
                'Breda',
                'Nijmegen',
                'Arnhem',
                'Haarlem',
            ],
            'IE' => [
                'Dublin',
                'Cork',
                'Galway',
                'Limerick',
                'Waterford',
                'Drogheda',
                'Kilkenny',
                'Sligo',
                'Dundalk',
                'Athlone',
                'Wexford',
                'Tralee',
            ],
            'PL' => [
                'Warsaw',
                'Kraków',
                'Wrocław',
                'Poznań',
                'Gdańsk',
                'Łódź',
                'Szczecin',
                'Lublin',
                'Katowice',
                'Białystok',
                'Gdynia',
                'Toruń',
            ],
            'NO' => [
                'Oslo',
                'Bergen',
                'Trondheim',
                'Stavanger',
                'Drammen',
                'Fredrikstad',
                'Kristiansand',
                'Tromsø',
                'Sandnes',
                'Ålesund',
                'Bodø',
            ],
            'AT' => [
                'Vienna',
                'Salzburg',
                'Innsbruck',
                'Graz',
                'Linz',
                'Klagenfurt',
                'Villach',
                'Wels',
                'St. Pölten',
                'Dornbirn',
                'Bregenz',
            ],
            'CH' => [
                'Zurich',
                'Geneva',
                'Basel',
                'Bern',
                'Lausanne',
                'Winterthur',
                'Lucerne',
                'St. Gallen',
                'Lugano',
                'Zug',
                'Fribourg',
            ],
            'BE' => [
                'Brussels',
                'Antwerp',
                'Ghent',
                'Bruges',
                'Liège',
                'Charleroi',
                'Namur',
                'Leuven',
                'Mechelen',
                'Hasselt',
                'Ostend',
            ],
            'UA' => [
                'Kyiv',
                'Kharkiv',
                'Odesa',
                'Lviv',
                'Dnipro',
                'Zaporizhzhia',
                'Vinnytsia',
                'Poltava',
                'Chernihiv',
                'Ivano-Frankivsk',
            ],
            'DK' => [
                'Copenhagen',
                'Aarhus',
                'Odense',
                'Aalborg',
                'Esbjerg',
                'Randers',
                'Kolding',
                'Horsens',
                'Vejle',
                'Roskilde',
            ],
            'FI' => [
                'Helsinki',
                'Espoo',
                'Tampere',
                'Oulu',
                'Turku',
                'Jyväskylä',
                'Lahti',
                'Kuopio',
                'Pori',
                'Vaasa',
                'Rovaniemi',
            ],
            'HR' => [
                'Zagreb',
                'Split',
                'Rijeka',
                'Osijek',
                'Zadar',
                'Pula',
                'Dubrovnik',
                'Šibenik',
                'Varaždin',
                'Karlovac',
            ],

            // Americas
            'US' => [
                'California',
                'New York',
                'Texas',
                'Florida',
                'Colorado',
                'Illinois',
                'Washington',
                'Massachusetts',
                'Arizona',
                'Oregon',
                'Georgia',
                'Pennsylvania',
                'North Carolina',
                'Virginia',
            ],
            'CA' => [
                'Toronto',
                'Vancouver',
                'Montreal',
                'Calgary',
                'Ottawa',
                'Edmonton',
                'Winnipeg',
                'Quebec City',
                'Halifax',
                'Victoria',
                'Saskatoon',
                'Regina',
            ],
            'BR' => [
                'São Paulo',
                'Rio de Janeiro',
                'Brasília',
                'Salvador',
                'Curitiba',
                'Fortaleza',
                'Belo Horizonte',
                'Manaus',
                'Porto Alegre',
                'Recife',
                'Florianópolis',
                'Campinas',
            ],
            'MX' => [
                'Mexico City',
                'Guadalajara',
                'Monterrey',
                'Puebla',
                'Tijuana',
                'Cancún',
                'Mérida',
                'Querétaro',
                'León',
                'Oaxaca',
                'San Miguel de Allende',
                'Playa del Carmen',
            ],
            'AR' => [
                'Buenos Aires',
                'Córdoba',
                'Rosario',
                'Mendoza',
                'La Plata',
                'Mar del Plata',
                'San Miguel de Tucumán',
                'Salta',
                'Santa Fe',
                'Neuquén',
                'Bariloche',
            ],
            'CL' => [
                'Santiago',
                'Valparaíso',
                'Concepción',
                'Viña del Mar',
                'Antofagasta',
                'La Serena',
                'Temuco',
                'Puerto Montt',
                'Iquique',
                'Punta Arenas',
            ],
            'CO' => [
                'Bogotá',
                'Medellín',
                'Cali',
                'Barranquilla',
                'Cartagena',
                'Santa Marta',
                'Bucaramanga',
                'Pereira',
                'Manizales',
                'Cúcuta',
            ],

            // Asia-Pacific
            'JP' => [
                'Tokyo',
                'Osaka',
                'Kyoto',
                'Yokohama',
                'Nagoya',
                'Sapporo',
                'Fukuoka',
                'Kobe',
                'Sendai',
                'Hiroshima',
                'Okinawa',
                'Nara',
                'Kanazawa',
            ],
            'KR' => [
                'Seoul',
                'Busan',
                'Incheon',
                'Daegu',
                'Daejeon',
                'Gwangju',
                'Ulsan',
                'Suwon',
                'Seongnam',
                'Goyang',
                'Jeju',
            ],
            'AU' => [
                'Sydney',
                'Melbourne',
                'Brisbane',
                'Perth',
                'Adelaide',
                'Gold Coast',
                'Canberra',
                'Newcastle',
                'Hobart',
                'Darwin',
                'Cairns',
                'Wollongong',
            ],
            'NZ' => [
                'Auckland',
                'Wellington',
                'Christchurch',
                'Hamilton',
                'Dunedin',
                'Tauranga',
                'Queenstown',
                'Napier',
                'Palmerston North',
                'Rotorua',
            ],
            'SG' => [
                'Central',
                'East',
                'West',
                'North',
                'North-East',
                'Marina Bay',
                'Orchard',
                'Jurong',
                'Tampines',
                'Woodlands',
            ],
            'IL' => [
                'Tel Aviv',
                'Jerusalem',
                'Haifa',
                'Rishon LeZion',
                'Petah Tikva',
                'Ashdod',
                'Netanya',
                'Beer Sheva',
                'Holon',
                'Eilat',
            ],
            'RU' => [
                'Moscow',
                'Saint Petersburg',
                'Novosibirsk',
                'Yekaterinburg',
                'Kazan',
                'Nizhny Novgorod',
                'Chelyabinsk',
                'Samara',
                'Rostov-on-Don',
                'Ufa',
                'Krasnoyarsk',
                'Sochi',
            ],

            // Africa
            'ZA' => [
                'Cape Town',
                'Johannesburg',
                'Durban',
                'Pretoria',
                'Port Elizabeth',
                'Bloemfontein',
                'East London',
                'Stellenbosch',
                'Pietermaritzburg',
                'Soweto',
            ],
        ];
    }
}
